In [1]:
from metab_processing.metab_travlr_config import PROJECT_DATA_DIR, DATA_DIR as METAB_DATA_DIR

import csv

def get_csv_header(file_path):
    with open(file_path, mode='r', encoding='utf-8') as f:
        reader = csv.reader(f)
        header = next(reader) # Fetches only the first row
        return header

header = get_csv_header(f'{METAB_DATA_DIR}/MERSCOPE/vz-ffpe-showcase/HumanBreastCancerPatient1/cell_by_gene.csv')

In [2]:
print(len(header))
print(header)

551
['cell', 'PDK4', 'CCL26', 'CX3CL1', 'PGLYRP1', 'CD4', 'SNAI2', 'TNFRSF17', 'ICAM3', 'TBX21', 'FAP', 'NFKB2', 'LAG3', 'TGFBR3', 'MMP11', 'XBP1', 'IL2RB', 'CTSG', 'GZMH', 'GZMB', 'NFKBIA', 'MMP2', 'CCL22', 'TSC2', 'TGFB1', 'CD79A', 'NKG7', 'HGF', 'SERPINE1', 'ACTA2', 'MPO', 'CSF3', 'WNT3', 'CCL2', 'CCL1', 'COL1A1', 'VTN', 'NFKB1', 'CCND1', 'IL23A', 'CDKN1B', 'IFNG', 'KLRB1', 'LOX', 'GZMK', 'IL12B', 'SELL', 'TGFB3', 'DUSP1', 'EGR1', 'KLRK1', 'TNFSF10', 'CXCR4', 'TWIST1', 'LRP1', 'SNAI1', 'CEACAM8', 'CDKN1A', 'SOX9', 'TNFSF9', 'CD70', 'FFAR2', 'CCR7', 'KLF2', 'SMO', 'RAF1', 'PLVAP', 'BST2', 'LGR6', 'CCNB1', 'PDGFRA', 'APC', 'TBX3', 'CDK4', 'IL6', 'BLK', 'FGFBP2', 'TLR2', 'MMP7', 'LYZ', 'LRP6', 'VWF', 'PROX1', 'CDH1', 'PDGFRB', 'FLT4', 'CREBBP', 'IL1B', 'BRD4', 'ELANE', 'EPCAM', 'AKT3', 'GNLY', 'KDR', 'PIK3CA', 'LAMC2', 'MCM6', 'FGF2', 'STAT3', 'ICAM1', 'PPARGC1A', 'CXCL9', 'MCM2', 'MSH3', 'EGF', 'STAP1', 'LAMP3', 'CDK6', 'PMS2', 'KLRG1', 'LGR5', 'CDK2', 'RB1', 'ITGAX', 'TP53', 'IFNAR1', 'FCGR2A', 'ACKR3', 'FABP2', 'SFRP2', 'GZMA', 'EGFR', 'DUSP6', 'TNFSF4', 'YAP1', 'ITGA1', 'WNT3A', 'FZD7', 'CSF1R', 'KIT', 'PREX2', 'SLC13A3', 'TNFRSF13C', 'CXCR5', 'CCR5', 'MAML1', 'ITGA5', 'CXCL16', 'LRP5', 'CXCR1', 'CXCL5', 'CCR1', 'CSF2', 'PLK1', 'STAT6', 'CD3D', 'CD14', 'MZB1', 'ITGB1', 'JUNB', 'CEBPB', 'FOS', 'CXCR6', 'IRS1', 'ESCO2', 'CCL11', 'BMP1', 'TMEM37', 'CXCL10', 'CXCL11', 'IGF1', 'CXCL8', 'BCL2L1', 'HAVCR2', 'CTSW', 'TLR1', 'XCR1', 'VEGFB', 'HRAS', 'CD248', 'KRAS', 'FOSL1', 'NOS2', 'MMP1', 'CD209', 'NCAM1', 'ZBED2', 'DERL3', 'RORC', 'CD276', 'CXCR2', 'ZEB1', 'HIF1A', 'ANGPT2', 'SOX2', 'CCR8', 'KIR3DL2', 'MARCO', 'FBLN1', 'IFITM1', 'CSF1', 'EPHB3', 'CD86', 'STING1', 'SOCS3', 'CCR4', 'IL3RA', 'PDGFB', 'ASCL2', 'TBK1', 'PTGDR2', 'IL1R2', 'BCL2', 'PDCD1', 'PKM', 'TBX10', 'CA7', 'SLC26A3', 'TNC', 'CAV1', 'ATF3', 'INSR', 'CCR6', 'CLEC14A', 'JAK1', 'HLA-DQA1', 'E2F1', 'IDH1', 'BAX', 'GATA3', 'DDIT3', 'CDCA7', 'CD5', 'KLRC1', 'PTPRC', 'CTNNB1', 'BIRC5', 'ATR', 'EZH2', 'CD8A', 'BRCA1', 'PROK2', 'COL11A1', 'TAP1', 'PKIB', 'TP63', 'LAMB3', 'IRF5', 'CCNE1', 'NF1', 'EPHA2', 'TGFBR2', 'KIR2DL4', 'FGF1', 'MFAP5', 'FOXM1', 'HLA-DRB1', 'FCER2', 'CLEC4C', 'TLR9', 'STAT1', 'CCL28', 'TGM2', 'MUC2', 'SOD2', 'CR2', 'PTGS2', 'FASLG', 'IFNGR1', 'XCL1', 'SH2D1B', 'ADAMTS4', 'CD244', 'ARG1', 'FCER1A', 'CD1E', 'CD1B', 'FCRL5', 'LMNA', 'IL6R', 'MKI67', 'S100A9', 'CD2', 'NRAS', 'VCAM1', 'CD40LG', 'JUN', 'AURKA', 'COL5A1', 'PTEN', 'MMRN2', 'VEGFA', 'CD40', 'MMP9', 'TREM2', 'MAFB', 'HDAC1', 'CXCR3', 'DES', 'DKK1', 'BAK1', 'CD28', 'C1QC', 'HLA-DMA', 'NRP1', 'TAP2', 'TGFBR1', 'PLA2G2A', 'COL4A1', 'NCR3', 'FOXP3', 'HLA-C', 'BMI1', 'MTOR', 'THBD', 'SPRY2', 'MYC', 'CA9', 'KITLG', 'CYBB', 'PCNA', 'CD83', 'TNFRSF4', 'TNFRSF18', 'LDHA', 'IL2RA', 'TEK', 'IFNB1', 'ELN', 'DNMT3A', 'IRF4', 'CD274', 'IFNGR2', 'MSR1', 'IFNAR2', 'TIGIT', 'GPX3', 'CD8B', 'IL4I1', 'AKT2', 'STAT4', 'CD79B', 'POU2AF1', 'CCL8', 'CCL7', 'CLCA1', 'MMRN1', 'SPP1', 'HLA-DRA', 'LGALS9', 'CXCL1', 'CXCL12', 'MYBL2', 'ITGA4', 'NFE2L2', 'TEAD4', 'PDCD1LG2', 'MET', 'ITGB2', 'SHARPIN', 'CX3CR1', 'CCR2', 'PDGFA', 'ROS1', 'CEACAM1', 'TSC1', 'CHEK2', 'RELA', 'ICOSLG', 'AKT1', 'CD207', 'PDK1', 'FGFR3', 'HLA-B', 'CMKLR1', 'PRKCA', 'IDO2', 'PPARD', 'HLA-DPA1', 'SIGLEC1', 'AMOTL2', 'FGFR1', 'TRAT1', 'SELP', 'CTLA4', 'IKZF4', 'TAPBP', 'MLH1', 'ICOS', 'NEDD4', 'FCGR3A', 'CHEK1', 'CD1C', 'IL5RA', 'TNF', 'EOMES', 'IKZF2', 'FN1', 'PLOD2', 'ZAP70', 'CSF3R', 'DIABLO', 'IL12RB2', 'WWTR1', 'SRPRB', 'IL12A', 'IL13', 'HDAC3', 'EPHA4', 'ARAF', 'VSIR', 'TMEM59', 'COL6A3', 'WNT5A', 'BTLA', 'SRC', 'NOS3', 'BUB1', 'CD80', 'MUC4', 'TGFB2', 'ENG', 'MUC1', 'CASP8', 'PIK3CG', 'BRAF', 'HLA-DPB1', 'CSF2RA', 'PDGFC', 'LEF1', 'TGFBI', 'CXCL2', 'RGMB', 'ANGPT1', 'IDO1', 'ITK', 'IKBKB', 'PAX5', 'PTK2', 'TEAD1', 'FLI1', 'CD3E', 'MS4A1', 'CD3G', 'TCF7L2', 'SMOC2', 'ETS1', 'CD22', 'IL22', 'CD19', 'MSH6', 'CD27', 'ERBB2', 'CD163', 'NLRC5', 'MSH2', 'PRTN3', 'ITGAM', 'CCR3', 'ROR1', 'ERBB3', 'SELPLG', 'PGF', 'NDUFA4L2', 'TCL1A', 'IGF1R', 'PECAM1', 'MAP2K1', 'MRC1', 'MMP12', 'MYH11', 'ICAM2', 'CD226', 'TNFRSF13B', 'CD68', 'AURKB', 'SMAD2', 'SMARCA4', 'STAT5A', 'CCR10', 'DNMT1', 'NCR1', 'IRF3', 'CCL5', 'IL21', 'TRAC', 'CCL3', 'CCL4', 'CDH5', 'TNFRSF9', 'RET', 'FLT1', 'KLRF1', 'CD160', 'EPHB4', 'CCL17', 'CIITA', 'CLDN5', 'CD177', 'VEGFC', 'AXIN2', 'PDPN', 'IL4', 'TRBC1', 'SERPINA1', 'FGFR2', 'ATM', 'PRF1', 'IL10', 'IL17A', 'NOTCH1', 'Blank-1', 'Blank-2', 'Blank-3', 'Blank-4', 'Blank-5', 'Blank-6', 'Blank-7', 'Blank-8', 'Blank-9', 'Blank-10', 'Blank-11', 'Blank-12', 'Blank-13', 'Blank-14', 'Blank-15', 'Blank-16', 'Blank-17', 'Blank-18', 'Blank-19', 'Blank-20', 'Blank-21', 'Blank-22', 'Blank-23', 'Blank-24', 'Blank-25', 'Blank-26', 'Blank-27', 'Blank-28', 'Blank-29', 'Blank-30', 'Blank-31', 'Blank-32', 'Blank-33', 'Blank-34', 'Blank-35', 'Blank-36', 'Blank-37', 'Blank-38', 'Blank-39', 'Blank-40', 'Blank-41', 'Blank-42', 'Blank-43', 'Blank-44', 'Blank-45', 'Blank-46', 'Blank-47', 'Blank-48', 'Blank-49', 'Blank-50']

In [3]:
import pandas as pd
sig_genes_csv = pd.read_csv(f'{METAB_DATA_DIR}/GSE208253/[ccc_results][cell_com_df_gp_sig].csv')
sig_genes_csv

,Unnamed: 0,Gene 1,Gene 2,C_p,Z,Z_pval,Z_FDR,C_norm_p,C_np,pval_np,FDR_np,C_norm_np,selected
0,0,SLC2A4,SLC2A10,1331.145015,2.107064,1.755600e-02,1.919854e-02,0.035395,103.256076,0.014925,0.021701,0.080770,True
1,2,SLC2A6,SLC2A6,3253.329618,6.474868,4.744744e-11,9.163668e-11,0.030848,425.412307,0.004975,0.007981,0.066433,True
2,5,SLC2A8,SLC2A10,3376.534216,4.640752,1.735715e-06,2.693352e-06,0.027839,904.080720,0.009950,0.015000,0.062419,True
3,8,SLC2A6,SLC2A11,4009.482162,6.032479,8.073189e-10,1.453174e-09,0.038018,383.605122,0.004975,0.007981,0.059904,True
4,9,SLC2A9,SLC2A10,1606.122774,2.415329,7.860495e-03,8.898674e-03,0.015062,356.928080,0.029851,0.041652,0.070479,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
648,893,SLC47A2,SLC47A2,5328.680993,10.605291,1.407936e-26,4.728145e-26,0.046319,1742.352829,0.004975,0.007981,0.145871,True
649,896,MFSD2A,MFSD2A,8242.673939,16.404801,8.835213e-61,7.163686e-60,0.068675,6651.411668,0.004975,0.007981,0.214653,True
650,897,RHBG,RHCG,8101.808405,9.033966,8.278022e-20,2.237303e-19,0.117134,6371.012277,0.004975,0.007981,3.153290,True
651,898,RHCG,RHCG,22232.636728,44.248018,0.000000e+00,0.000000e+00,0.179303,242641.244152,0.004975,0.007981,0.757407,True
652,899,RHBG,RHBG,2405.979220,4.788447,8.403829e-07,1.324597e-06,0.034785,90.787725,0.004975,0.007981,0.044935,True

In [4]:
# shows only sig gene pairs
all(sig_genes_csv['FDR_np'] <= 0.05)

True

In [5]:
all_sig_genes = set(sig_genes_csv['Gene 1']).union(set(sig_genes_csv['Gene 2']))

In [6]:
print(len(all_sig_genes))

177

In [7]:
intersect = all_sig_genes.intersection(header)

In [8]:
'IDH1' in header

True

In [9]:
print(intersect)

{'SLC13A3', 'LRP1', 'MSR1', 'TAP1'}

In [10]:
import scanpy as sc
adata = sc.read_h5ad(f'{METAB_DATA_DIR}/Xenium/Human_Lung/adata.h5ad')

In [11]:
intersect = all_sig_genes.intersection(adata.var_names)

In [12]:
len(intersect)

63

In [13]:
print(list(intersect))

['SLC9A1', 'ABCC1', 'SLC16A1', 'SLCO2B1', 'TAP1', 'ORAI2', 'SLC2A4', 'SLC38A7', 'CLCN3', 'SLC5A1', 'SLC6A2', 'FOLR1', 'AQP9', 'SLC1A3', 'CD36', 'SLC19A1', 'SLC23A2', 'FOLR2', 'ABCA1', 'SLC12A2', 'SLC6A9', 'CPT1A', 'SLC7A11', 'SLC2A1', 'ABCC2', 'AQP7', 'SLC16A9', 'ABCC4', 'SLC29A1', 'AQP5', 'ABCC3', 'CLCN5', 'ABCB1', 'SLC20A2', 'SLC39A8', 'SLC12A6', 'SLC7A5', 'ATP7A', 'SLC11A2', 'SLC22A5', 'SLC15A1', 'SLC11A1', 'SLC1A5', 'SLC22A4', 'SLC2A3', 'MSR1', 'LRP1', 'SLC40A1', 'SLC7A7', 'SCNN1A', 'SLC22A1', 'SLC24A1', 'SLC3A2', 'SLC5A3', 'SLC43A2', 'SLC2A9', 'CD38', 'SLCO1B3', 'ORAI3', 'SLC29A3', 'SLC26A2', 'SCNN1G', 'SCARB1']

In [14]:
print(all_sig_genes - intersect)

{'SLC6A11', 'SLC27A4', 'SLC1A4', 'SLC26A11', 'SLC30A6', 'SLC43A3', 'SLC36A1', 'SLC16A5', 'SLC6A8', 'SLCO3A1', 'AQP1', 'SLC22A3', 'SLC16A3', 'SLC38A9', 'SLC38A2', 'SLC2A12', 'SLC26A6', 'SLC4A8', 'SLC27A1', 'SLC47A2', 'SLC2A11', 'SLC27A5', 'SLC20A1', 'SLC41A2', 'SLC39A4', 'AMN', 'SLC38A1', 'RBP1', 'TCN2', 'SLC36A4', 'SLC2A13', 'SLC29A2', 'SLC13A3', 'FLVCR1', 'SLC8A1', 'FABP5', 'SLC7A1', 'SLC15A4', 'SLC4A7', 'SLC7A2', 'SLC19A2', 'FABP4', 'SLC4A3', 'SLC36A2', 'CLCN2', 'SLC31A1', 'SLC44A2', 'SLC26A9', 'SLC12A7', 'ABCC5', 'SLC39A1', 'SLC7A6', 'TCN1', 'SLC6A14', 'GOT2', 'SLC44A1', 'ORAI1', 'SLC6A6', 'AQP3', 'SLC13A5', 'SLC52A3', 'SLC5A6', 'SLC16A10', 'STRA6', 'SLC15A3', 'SLC27A3', 'SLC39A10', 'SLC28A3', 'SLC31A2', 'CRABP1', 'SLC2A6', 'SLC30A5', 'SLC30A4', 'SLC30A1', 'SLC38A5', 'SLC41A1', 'SLC39A7', 'SLC34A2', 'SLC2A8', 'SLC38A6', 'SLCO2A1', 'SLC5A10', 'SLC7A8', 'SLC39A2', 'SLC39A6', 'SLC24A2', 'RHBG', 'SLC25A32', 'SLC16A11', 'SLC46A1', 'SLC6A15', 'SLC41A3', 'SLC4A11', 'SLC4A2', 'SLC44A4', 'SLC35F5', 'SLC15A2', 'SLC24A3', 'SLC39A3', 'SLC12A4', 'SCNN1B', 'SLC52A2', 'CRABP2', 'SLC38A4', 'SLC16A7', 'SLCO4A1', 'SLC2A10', 'SLC52A1', 'SLC44A3', 'SLC16A2', 'RHCG', 'SLC43A1', 'MFSD2A', 'SLC2A5'}

In [15]:
cell_sig_genes_csv = pd.read_csv(f'{METAB_DATA_DIR}/GSE208253/[ct_ccc_results][cell_com_df_m].csv')
cell_sig_genes_csv

,Unnamed: 0,Cell Type 1,Cell Type 2,metabolite,C_p,Z,Z_pval,Z_FDR,C_np,pval_np,FDR_np,selected
0,0,T cell,T cell,"(3a,5b,7a)-23-Carboxy-7-hydroxy-24-norcholan-3...",277.588230,3.281680,5.159533e-04,1.119853e-03,48.264560,0.209790,0.237100,False
1,1,T cell,T cell,17a-Ethynylestradiol,140.967000,3.726470,9.709010e-05,2.483599e-04,0.048046,0.295704,0.324595,False
2,2,T cell,T cell,"1b,3a,12a-Trihydroxy-5b-cholanoic acid",277.588230,3.281680,5.159533e-04,1.119853e-03,48.264560,0.209790,0.237100,False
3,3,T cell,T cell,2-Hydroxychlorpropamide,287.920780,5.381932,3.684534e-08,1.255900e-07,5.345208,0.080919,0.105140,False
4,4,T cell,T cell,25-Hydroxycholesterol,29.848173,0.789038,2.150449e-01,2.632921e-01,157.031780,0.094905,0.121657,False
...,...,...,...,...,...,...,...,...,...,...,...,...
568,568,other,other,alpha-Ketoisovaleric acid,13948.529000,29.029024,1.415801e-185,2.458345e-184,25426.094000,0.000999,0.001829,True
569,569,other,other,alpha-Linolenic acid,843.535460,3.040661,1.180298e-03,2.261908e-03,42.603714,0.004995,0.008272,True
570,570,other,other,alpha-Tocopherol,1710.936200,6.167348,3.472241e-10,1.275381e-09,566.646500,0.013986,0.022199,True
571,571,other,other,beta-Alanine,438.198150,1.579557,5.710422e-02,7.790648e-02,35.703760,0.010989,0.017687,True
572,572,other,other,gamma-Linolenic acid,843.535460,3.040661,1.180298e-03,2.261908e-03,42.603714,0.004995,0.008272,True

In [16]:
vis_adata = sc.read_h5ad(f'{METAB_DATA_DIR}/GSE208253/processed_adata_sub.h5ad')

In [17]:
vis_adata.uns['ct_ccc_results'].keys()

dict_keys(['cell_com_df_gp', 'cell_com_df_gp_sig', 'cell_com_df_m', 'cell_com_df_m_sig', 'np', 'p'])

In [18]:
sig_cell_df = vis_adata.uns['ct_ccc_results']['cell_com_df_gp_sig']
sig_cell_type_genes = set(sig_cell_df['Gene 1']).union(set(sig_cell_df['Gene 2']))
len(sig_cell_type_genes)

172

In [19]:
intersect = sig_cell_type_genes.intersection(adata.var_names)
print(len(intersect))

61

In [20]:
print(intersect)

{'SLC9A1', 'ABCC1', 'SLC16A1', 'SLCO2B1', 'TAP1', 'ORAI2', 'SLC2A4', 'SLC38A7', 'CLCN3', 'SLC5A1', 'SLC6A2', 'SLC1A3', 'CD36', 'SLC19A1', 'SLC23A2', 'FOLR2', 'ABCA1', 'SLC12A2', 'SLC6A9', 'CPT1A', 'SLC7A11', 'SLC2A1', 'ABCC2', 'AQP7', 'SLC16A9', 'ABCC4', 'SLC29A1', 'AQP5', 'ABCC3', 'CLCN5', 'ABCB1', 'SLC20A2', 'SLC39A8', 'SLC12A6', 'SLC7A5', 'ATP7A', 'SLC11A2', 'SLC22A5', 'SLC15A1', 'SLC11A1', 'SLC1A5', 'SLC22A4', 'SLC2A3', 'MSR1', 'LRP1', 'SLC40A1', 'SLC7A7', 'SCNN1A', 'SLC22A1', 'SLC24A1', 'SLC3A2', 'SLC5A3', 'SLC43A2', 'SLC2A9', 'CD38', 'SLCO1B3', 'ORAI3', 'SLC29A3', 'SLC26A2', 'SCNN1G', 'SCARB1'}

In [21]:
print(sig_cell_type_genes - intersect)

{'SLC6A11', 'SLC27A4', 'SLC1A4', 'SLC26A11', 'SLC30A6', 'SLC43A3', 'SLC36A1', 'SLC16A5', 'SLC6A8', 'SLCO3A1', 'AQP1', 'SLC22A3', 'SLC16A3', 'SLC38A9', 'SLC38A2', 'SLC2A12', 'SLC26A6', 'SLC4A8', 'SLC27A1', 'SLC47A2', 'SLC2A11', 'SLC27A5', 'SLC20A1', 'SLC41A2', 'SLC39A4', 'AMN', 'SLC38A1', 'RBP1', 'TCN2', 'SLC36A4', 'SLC29A2', 'SLC13A3', 'FLVCR1', 'FABP5', 'SLC7A1', 'SLC15A4', 'SLC4A7', 'SLC7A2', 'SLC19A2', 'FABP4', 'SLC4A3', 'SLC36A2', 'SLC31A1', 'SLC44A2', 'SLC26A9', 'SLC12A7', 'ABCC5', 'SLC39A1', 'SLC7A6', 'TCN1', 'SLC6A14', 'GOT2', 'SLC44A1', 'ORAI1', 'SLC6A6', 'AQP3', 'SLC13A5', 'SLC52A3', 'SLC5A6', 'SLC16A10', 'STRA6', 'SLC15A3', 'SLC27A3', 'SLC39A10', 'SLC28A3', 'SLC31A2', 'CRABP1', 'SLC2A6', 'SLC30A5', 'SLC30A4', 'SLC30A1', 'SLC38A5', 'SLC41A1', 'SLC39A7', 'SLC34A2', 'SLC2A8', 'SLC38A6', 'SLCO2A1', 'SLC5A10', 'SLC7A8', 'SLC39A2', 'SLC39A6', 'SLC24A2', 'RHBG', 'SLC25A32', 'SLC16A11', 'SLC46A1', 'SLC6A15', 'SLC41A3', 'SLC4A11', 'SLC4A2', 'SLC44A4', 'SLC35F5', 'SLC15A2', 'SLC24A3', 'SLC39A3', 'SLC12A4', 'SCNN1B', 'SLC52A2', 'CRABP2', 'SLC38A4', 'SLC16A7', 'SLCO4A1', 'SLC2A10', 'SLC52A1', 'SLC44A3', 'SLC16A2', 'RHCG', 'SLC43A1', 'MFSD2A', 'SLC2A5'}

In [22]:
intersect = all_sig_genes.intersection(sig_cell_type_genes)
len(intersect)

172